name: eyo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.2
  camera: ^0.10.5+6
  google_ml_kit: ^0.14.0
  image_picker: ^1.0.4
  #mobile_scanner: ^3.5.5
  postgres: ^3.0.5
  http: ^0.13.6
  flutter_svg: ^2.0.9
  flutter_bcrypt: ^1.0.8
  crypto: ^3.0.3
  #flutter_ocr_sdk: ^1.1.4
  #flutter_scalable_ocr: ^2.0.0
  googleapis_auth: ^1.4.1
  googleapis: ^12.0.0
  images_picker: ^1.2.11
  #flutter_camera_ml_vision: ^3.0.1
  permission_handler: ^11.0.1
  google_mlkit_text_recognition: ^0.6.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Zen-R
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Regular.ttf
    - family: Zen-M
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Medium.ttf
    - family: Zen-L
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Light.ttf
    - family: Zen-B
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Bold.ttf
    - family: Zen-BL
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Black.ttf
  assets:
    - assets/image/
    - assets/image/nutri_image.jpg
    - assets/image/protein_image.png
    - assets/image/fat_image.png
    - assets/image/carbs_image.png