name: eyo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Zen-R
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Regular.ttf
    - family: Zen-M
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Medium.ttf
    - family: Zen-L
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Light.ttf
    - family: Zen-B
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Bold.ttf
    - family: Zen-BL
      fonts:
        - asset: assets/fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Black.ttf

